### ISSUE TITLE
면접스터디

### ISSUE THREAD

**Issue by smallerhand** [smallerhand/newbie#3]
취업준비하면서 면접이 정말 준비가 많이 필요한 부분인데도 불구하고 따로 스터디를 안 만들면 준비가 어렵고, 일단 면접 분위기를 만들어보는 것만으로도 상당히 도움이 된다고 느꼈습니다. 주변에 잘 취업한 사람들 봐도 면접스터디가 중요하다고 생각하느 사람들이 많았고요~ 그 중에서도 면접관 : 피면접자 역할을 바꿔가면서 해보는 모의면접이 상당히 도움이 됐다는 얘기를 들었고, 제가 보기에도 괜찮은 방법 같아서 필요성을 느끼는 분들과 함께 해보려고 합니다.

이게 왜 도움이 되냐면, 우리가 면접관의 역할에서 생각해볼 기회가 없기 때문에.. 역할을 바꿔보면서 자기 자신을 좀 더 객관적으로 보고 분석할 수 있게 되는 것 같습니다. 그리고 혼자 마인드 트레이닝만 하는 것과 역할극 하듯이 상황이 주어진 경우에 받아들이는 느낌이 많이 달라서인 것 같습니다.

참가하실 분은 댓글 달아주세요~

**Comment by audwnd951** [comment]
참가합니다

**Comment by ghost** [comment]
참가합니다
